# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsmConnect < Formula
  desc "CLI tool for connecting to AWS EC2 instances via SSM Session Manager"
  homepage "https://github.com/eugenetaranov/aws-ssm-connect"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eugenetaranov/aws-ssm-connect/releases/download/v0.1.7/aws-ssm-connect_0.1.7_darwin_amd64.tar.gz"
      sha256 "94d1a2d1ea9c6a71a93f51166725edcab6f9f8c94a433f468153dd6a4d0dbfb1"

      def install
        bin.install "aws-ssm-connect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eugenetaranov/aws-ssm-connect/releases/download/v0.1.7/aws-ssm-connect_0.1.7_darwin_arm64.tar.gz"
      sha256 "ee68de6c48ea12cab592f49aa9a60a0734cc3d69aa831b4f5b2d5aa2bf9bdfdc"

      def install
        bin.install "aws-ssm-connect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/aws-ssm-connect/releases/download/v0.1.7/aws-ssm-connect_0.1.7_linux_amd64.tar.gz"
      sha256 "e6770c666ff7606a5762659e7379cf3e3ed651a304ca0cc18136995bfe2c5dd6"
      def install
        bin.install "aws-ssm-connect"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/aws-ssm-connect/releases/download/v0.1.7/aws-ssm-connect_0.1.7_linux_arm64.tar.gz"
      sha256 "c0f0e0276f82cba98802ea931d7db2da1a5a636fb6301f486de322b764a25b1e"
      def install
        bin.install "aws-ssm-connect"
      end
    end
  end

  def caveats
    <<~EOS
      This tool requires the AWS Session Manager Plugin.
      Install it with: brew install --cask session-manager-plugin
    EOS
  end

  test do
    system "#{bin}/aws-ssm-connect", "--version"
  end
end
