# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bolt < Formula
  desc "Configuration management and system bootstrapping tool inspired by Ansible"
  homepage "https://github.com/eugenetaranov/bolt"
  version "1.0.14"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eugenetaranov/bolt/releases/download/v1.0.14/bolt_1.0.14_darwin_amd64.tar.gz"
      sha256 "23554072b0c57c3b9a9666e997782fe5926cbcf62ca2a7a2d5f63654cda1f03d"

      define_method(:install) do
        bin.install "bolt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eugenetaranov/bolt/releases/download/v1.0.14/bolt_1.0.14_darwin_arm64.tar.gz"
      sha256 "829616f391451b73b7746c3d0ceda75fa7e1b5333ea13353d7507b8b9c86e317"

      define_method(:install) do
        bin.install "bolt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/bolt/releases/download/v1.0.14/bolt_1.0.14_linux_amd64.tar.gz"
      sha256 "4a760aa23205d0939bf4aec2f92b6fc3afe733b724aeba3892c3ede6f50c0a9d"
      define_method(:install) do
        bin.install "bolt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/bolt/releases/download/v1.0.14/bolt_1.0.14_linux_arm64.tar.gz"
      sha256 "cb79290fc7cf6036fffdb945a7d24d4b7a8611f8e3c3b0916232c92436a08dde"
      define_method(:install) do
        bin.install "bolt"
      end
    end
  end

  test do
    system "#{bin}/bolt", "--version"
  end
end
