# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bolt < Formula
  desc "Configuration management and system bootstrapping tool inspired by Ansible"
  homepage "https://github.com/eugenetaranov/bolt"
  version "1.0.29"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eugenetaranov/bolt/releases/download/v1.0.29/bolt_1.0.29_darwin_amd64.tar.gz"
      sha256 "5b10f23ce07160fd6e6172d14355aea1c75169f1b9df4e1de256e98625ec57ac"

      define_method(:install) do
        bin.install "bolt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eugenetaranov/bolt/releases/download/v1.0.29/bolt_1.0.29_darwin_arm64.tar.gz"
      sha256 "123c52aac5fab9c29bf858b41ef10c4fedb8ea31ba3013c19305eb1446942fe4"

      define_method(:install) do
        bin.install "bolt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/bolt/releases/download/v1.0.29/bolt_1.0.29_linux_amd64.tar.gz"
      sha256 "04ae81a8e6de4833c92419045d6ce019212d883e2791191189f88d7882c0aa7d"
      define_method(:install) do
        bin.install "bolt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/bolt/releases/download/v1.0.29/bolt_1.0.29_linux_arm64.tar.gz"
      sha256 "b6c8b824c8b37bf38761f6fac2550ba76c6e6c2c17225dee969420e5358f6035"
      define_method(:install) do
        bin.install "bolt"
      end
    end
  end

  test do
    system "#{bin}/bolt", "--version"
  end
end
