# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bolt < Formula
  desc "Configuration management and system bootstrapping tool inspired by Ansible"
  homepage "https://github.com/eugenetaranov/bolt"
  version "1.0.27"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eugenetaranov/bolt/releases/download/v1.0.27/bolt_1.0.27_darwin_amd64.tar.gz"
      sha256 "f654aee3e6e7fadddcc661322494191154a6f00f0bb7ff47a1dea9f76ae08791"

      define_method(:install) do
        bin.install "bolt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eugenetaranov/bolt/releases/download/v1.0.27/bolt_1.0.27_darwin_arm64.tar.gz"
      sha256 "b716c6940c20c7e86d2f7f456b8eae1474729f8ceb11942467ab79d38b4cbf58"

      define_method(:install) do
        bin.install "bolt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/bolt/releases/download/v1.0.27/bolt_1.0.27_linux_amd64.tar.gz"
      sha256 "ace75cc16810e20b05fcc2449198753e3fbf5ed45a92d5b7d2dc0237bf976381"
      define_method(:install) do
        bin.install "bolt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/bolt/releases/download/v1.0.27/bolt_1.0.27_linux_arm64.tar.gz"
      sha256 "489052d4fbda6ba71b5b5403729867dbe2dc42df32f29a70d0236d2d837b89f2"
      define_method(:install) do
        bin.install "bolt"
      end
    end
  end

  test do
    system "#{bin}/bolt", "--version"
  end
end
