# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jiractl < Formula
  desc "CLI tool for interacting with Jira"
  homepage "https://github.com/eugenetaranov/jiractl"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eugenetaranov/jiractl/releases/download/v0.2.0/jiractl_0.2.0_darwin_amd64.tar.gz"
      sha256 "30258378ed67c4d9fd048b4d210476e98260f456d697f0429c34ae2c2e19c520"

      define_method(:install) do
        bin.install "jiractl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eugenetaranov/jiractl/releases/download/v0.2.0/jiractl_0.2.0_darwin_arm64.tar.gz"
      sha256 "240df990bef2f314bb06a6f615eef72be3b585e68785adf425a8c5f79ab1a2e9"

      define_method(:install) do
        bin.install "jiractl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/jiractl/releases/download/v0.2.0/jiractl_0.2.0_linux_amd64.tar.gz"
      sha256 "dcee03eada999dd3b7caa2db3ba6920a1e27335e406f208ca35abf73e9d2e177"
      define_method(:install) do
        bin.install "jiractl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/jiractl/releases/download/v0.2.0/jiractl_0.2.0_linux_arm64.tar.gz"
      sha256 "9f5e0bfa4ea7bea7aa709d3543c869f196371c9f35f5983cbd7c0f8b515b124a"
      define_method(:install) do
        bin.install "jiractl"
      end
    end
  end

  test do
    system "#{bin}/jiractl", "--version"
  end
end
