# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jiractl < Formula
  desc "CLI tool for interacting with Jira"
  homepage "https://github.com/eugenetaranov/jiractl"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eugenetaranov/jiractl/releases/download/v0.1.3/jiractl_0.1.3_darwin_amd64.tar.gz"
      sha256 "5bbaac4ee256f456eeda51cc4314bd85f6287f0147fbf9f05db040624d231a6d"

      def install
        bin.install "jiractl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eugenetaranov/jiractl/releases/download/v0.1.3/jiractl_0.1.3_darwin_arm64.tar.gz"
      sha256 "7df9e87cb47a301c6faa794e35ffb7049a70278815411a4fe0cae923b4ffdae7"

      def install
        bin.install "jiractl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/jiractl/releases/download/v0.1.3/jiractl_0.1.3_linux_amd64.tar.gz"
      sha256 "7a5a5e8c8808516ff12e7a6c26c2533bccd16c7db749f4a63a52935cfdd1e8c5"
      def install
        bin.install "jiractl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/jiractl/releases/download/v0.1.3/jiractl_0.1.3_linux_arm64.tar.gz"
      sha256 "86ab968cafcf85a38149d0b1c5f095bb8a7a1c29eca1d4d35f0aefdd735aa063"
      def install
        bin.install "jiractl"
      end
    end
  end

  test do
    system "#{bin}/jiractl", "--version"
  end
end
