# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jiractl < Formula
  desc "CLI tool for interacting with Jira"
  homepage "https://github.com/eugenetaranov/jiractl"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eugenetaranov/jiractl/releases/download/v0.1.5/jiractl_0.1.5_darwin_amd64.tar.gz"
      sha256 "46a94decc5e73bd7d8bb6ec3302bcd55c6719511c428c5d7e89e91cc5f92ba54"

      def install
        bin.install "jiractl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eugenetaranov/jiractl/releases/download/v0.1.5/jiractl_0.1.5_darwin_arm64.tar.gz"
      sha256 "41cf447baa56cce2301e72774936774b611f60807ade876369ef92b93b1fc62c"

      def install
        bin.install "jiractl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/jiractl/releases/download/v0.1.5/jiractl_0.1.5_linux_amd64.tar.gz"
      sha256 "b394c2e062dd9eb4e7174a5bdb81c3c2a8b9b94124cf3e2749ec8c6ea9414c53"
      def install
        bin.install "jiractl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/jiractl/releases/download/v0.1.5/jiractl_0.1.5_linux_arm64.tar.gz"
      sha256 "9645cd04f23b590dc59a03a0f0510a4fc6718d86db4a8ddfd7bc991ab4342b94"
      def install
        bin.install "jiractl"
      end
    end
  end

  test do
    system "#{bin}/jiractl", "--version"
  end
end
