# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mysqlmonitoring < Formula
  desc "MySQL lock monitor - detect lock contention, long transactions, and deadlocks"
  homepage "https://github.com/eugenetaranov/mysqlmonitoring"
  version "0.1.0"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eugenetaranov/mysqlmonitoring/releases/download/v0.1.0/mysqlmonitoring_0.1.0_darwin_amd64.tar.gz"
      sha256 "a6569ed8bc146f4b76e8bfd99c9d3fafcc61578a1afd25f551727cb504de0cf7"

      define_method(:install) do
        bin.install "mysqlmonitoring"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eugenetaranov/mysqlmonitoring/releases/download/v0.1.0/mysqlmonitoring_0.1.0_darwin_arm64.tar.gz"
      sha256 "219a596ba65c5b26b540a6d88ba42815eccf8a2287f6fbe7d466dc201960b9e2"

      define_method(:install) do
        bin.install "mysqlmonitoring"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/mysqlmonitoring/releases/download/v0.1.0/mysqlmonitoring_0.1.0_linux_amd64.tar.gz"
      sha256 "3e53e0a308f5b67a76b3e15ccec63919ce73b52cf63f4cad6b2c0d5de757fdac"
      define_method(:install) do
        bin.install "mysqlmonitoring"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/mysqlmonitoring/releases/download/v0.1.0/mysqlmonitoring_0.1.0_linux_arm64.tar.gz"
      sha256 "d4010913f0d22e7a854f08157074a494836eec99d00da7ca8f0e34dd2ceea46a"
      define_method(:install) do
        bin.install "mysqlmonitoring"
      end
    end
  end

  test do
    system "#{bin}/mysqlmonitoring", "--version"
  end
end
