# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mysqlmonitoring < Formula
  desc "MySQL lock monitor - detect lock contention, long transactions, and deadlocks"
  homepage "https://github.com/eugenetaranov/mysqlmonitoring"
  version "0.1.1"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eugenetaranov/mysqlmonitoring/releases/download/v0.1.1/mysqlmonitoring_0.1.1_darwin_amd64.tar.gz"
      sha256 "12888ef84a7976c9399c9eca2bdd28e9a30703eb4449c2ae8f40bbab9f57a366"

      define_method(:install) do
        bin.install "mysqlmonitoring"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eugenetaranov/mysqlmonitoring/releases/download/v0.1.1/mysqlmonitoring_0.1.1_darwin_arm64.tar.gz"
      sha256 "2374187ee71b19a4a3825d621abddf8e49c3a32c21dd3582f54d0b8b9c03f684"

      define_method(:install) do
        bin.install "mysqlmonitoring"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/mysqlmonitoring/releases/download/v0.1.1/mysqlmonitoring_0.1.1_linux_amd64.tar.gz"
      sha256 "2bb55d283a52416203e26ed455b770ed4fc28a26ae192fc3ed1b75cc6c52a034"
      define_method(:install) do
        bin.install "mysqlmonitoring"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/mysqlmonitoring/releases/download/v0.1.1/mysqlmonitoring_0.1.1_linux_arm64.tar.gz"
      sha256 "183b8eb64c6bc2973899bcc6bb7d5cbb2d2e584f849cf13e680391035465ebfe"
      define_method(:install) do
        bin.install "mysqlmonitoring"
      end
    end
  end

  test do
    system "#{bin}/mysqlmonitoring", "--version"
  end
end
