# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pmox < Formula
  desc "Multipass-style CLI for launching and managing VMs on Proxmox VE"
  homepage "https://github.com/eugenetaranov/pmox"
  version "0.16.0"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eugenetaranov/pmox/releases/download/v0.16.0/pmox_0.16.0_darwin_amd64.tar.gz"
      sha256 "4088880059d95e21773199a64a22c3ef07dfa9a8e95c1b34285c86c2654cc89b"

      define_method(:install) do
        bin.install "pmox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eugenetaranov/pmox/releases/download/v0.16.0/pmox_0.16.0_darwin_arm64.tar.gz"
      sha256 "73c991d006f038a583661d56d7477c7faa4d03b1b7f7a2b4f3aea1b79ab2d6a1"

      define_method(:install) do
        bin.install "pmox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/pmox/releases/download/v0.16.0/pmox_0.16.0_linux_amd64.tar.gz"
      sha256 "37d821f704853e8c7edd1720b2c59e46471b1a24401ea65a970851713f6b1bb0"
      define_method(:install) do
        bin.install "pmox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/pmox/releases/download/v0.16.0/pmox_0.16.0_linux_arm64.tar.gz"
      sha256 "f70d96ca38f530e942e7629d0b26d22fc995eb4b26e10e8aeaed5cd6a0fa93c8"
      define_method(:install) do
        bin.install "pmox"
      end
    end
  end

  test do
    system "#{bin}/pmox", "--version"
  end
end
