# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pmox < Formula
  desc "Multipass-style CLI for launching and managing VMs on Proxmox VE"
  homepage "https://github.com/eugenetaranov/pmox"
  version "0.8.0"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eugenetaranov/pmox/releases/download/v0.8.0/pmox_0.8.0_darwin_amd64.tar.gz"
      sha256 "424137ef1922cd55f0d297df865951d2622180ba15c6172da70b08ae3163cd04"

      define_method(:install) do
        bin.install "pmox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eugenetaranov/pmox/releases/download/v0.8.0/pmox_0.8.0_darwin_arm64.tar.gz"
      sha256 "f42d4b4064ba92d2989f2475bb6d4eb2e1912a05d2f73432771abc21ac8375f5"

      define_method(:install) do
        bin.install "pmox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/pmox/releases/download/v0.8.0/pmox_0.8.0_linux_amd64.tar.gz"
      sha256 "28017f237b47c4cb3b99103ec2507ccbb72d6bf708ae59ce464e4df16c85e9e3"
      define_method(:install) do
        bin.install "pmox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/pmox/releases/download/v0.8.0/pmox_0.8.0_linux_arm64.tar.gz"
      sha256 "feef8f8cb15c1de42d021d5a235f2231f2a6732eaa9d9ea3e8dafc36093d7acc"
      define_method(:install) do
        bin.install "pmox"
      end
    end
  end

  test do
    system "#{bin}/pmox", "--version"
  end
end
