# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pmox < Formula
  desc "Multipass-style CLI for launching and managing VMs on Proxmox VE"
  homepage "https://github.com/eugenetaranov/pmox"
  version "0.1.4"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eugenetaranov/pmox/releases/download/v0.1.4/pmox_0.1.4_darwin_amd64.tar.gz"
      sha256 "5a61c4df028b827708f9b9d61cd7b00ff55fcb3d278703ffe3358b8d4b9c8c93"

      define_method(:install) do
        bin.install "pmox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eugenetaranov/pmox/releases/download/v0.1.4/pmox_0.1.4_darwin_arm64.tar.gz"
      sha256 "6a2cf8e33b156b396e9549e4207c5514036ec431ac95351f721419f32e0054a1"

      define_method(:install) do
        bin.install "pmox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/pmox/releases/download/v0.1.4/pmox_0.1.4_linux_amd64.tar.gz"
      sha256 "93c01b1abe4598887b6d52d0208eb1464db35ad0fed1226a35ede957bb38ef3b"
      define_method(:install) do
        bin.install "pmox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/pmox/releases/download/v0.1.4/pmox_0.1.4_linux_arm64.tar.gz"
      sha256 "8d1a36d674fb393c5e124677ac433e1fd5fd05b145323c3f2e96afa56f2ca20f"
      define_method(:install) do
        bin.install "pmox"
      end
    end
  end

  test do
    system "#{bin}/pmox", "--version"
  end
end
