# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssmsearch < Formula
  desc "AWS SSM Parameter Store CLI with fuzzy search and caching"
  homepage "https://github.com/eugenetaranov/ssmsearch"
  version "0.1.6"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eugenetaranov/ssmsearch/releases/download/v0.1.6/ssmsearch_0.1.6_darwin_amd64.tar.gz"
      sha256 "a220108c0f36b0135cb4a58f999d1cf25820ffcf0568532d285d403364b6c252"

      define_method(:install) do
        bin.install "ssmsearch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eugenetaranov/ssmsearch/releases/download/v0.1.6/ssmsearch_0.1.6_darwin_arm64.tar.gz"
      sha256 "f6cfb9fec17236bb33321b75b34910466e592ef0bb0f725f007f68d8b1561acb"

      define_method(:install) do
        bin.install "ssmsearch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/ssmsearch/releases/download/v0.1.6/ssmsearch_0.1.6_linux_amd64.tar.gz"
      sha256 "a264a3b74c2c472e7353b4b0dd6a07718c11d2bc6c510d99dfe3c1bfae68dc75"
      define_method(:install) do
        bin.install "ssmsearch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/ssmsearch/releases/download/v0.1.6/ssmsearch_0.1.6_linux_arm64.tar.gz"
      sha256 "4692998608e162bfb2a0af549467069511a12efd5144afd2014e4d8297f162bc"
      define_method(:install) do
        bin.install "ssmsearch"
      end
    end
  end

  test do
    system "#{bin}/ssmsearch", "-v"
  end
end
