# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssmsearch < Formula
  desc "AWS SSM Parameter Store CLI with fuzzy search and caching"
  homepage "https://github.com/eugenetaranov/ssmsearch"
  version "0.1.8"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eugenetaranov/ssmsearch/releases/download/v0.1.8/ssmsearch_0.1.8_darwin_amd64.tar.gz"
      sha256 "dbf3f32c236a74259c48c267dc9e87db0d07889bdf355ff1fbbc04fa42d618c9"

      define_method(:install) do
        bin.install "ssmsearch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eugenetaranov/ssmsearch/releases/download/v0.1.8/ssmsearch_0.1.8_darwin_arm64.tar.gz"
      sha256 "ab5e74cca941b16c930ec10d275345c8439011fb37b1c46e65c6b40e53b139f9"

      define_method(:install) do
        bin.install "ssmsearch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/ssmsearch/releases/download/v0.1.8/ssmsearch_0.1.8_linux_amd64.tar.gz"
      sha256 "c53331b3f157b499919603cadc77a86c30cb2fc170dfb29ad63241f7bd2356ec"
      define_method(:install) do
        bin.install "ssmsearch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eugenetaranov/ssmsearch/releases/download/v0.1.8/ssmsearch_0.1.8_linux_arm64.tar.gz"
      sha256 "aadadd6d6b3c32b5bfa41398f1b5e5ebcc550b31897cdbc66073bdbb65e855f8"
      define_method(:install) do
        bin.install "ssmsearch"
      end
    end
  end

  test do
    system "#{bin}/ssmsearch", "-v"
  end
end
